import { defineConfig, type OxlintConfig } from 'oxlint';

export const typescript: OxlintConfig = defineConfig({
  categories: {
    correctness: 'error',
    nursery: 'error',
    pedantic: 'error',
    perf: 'error',
    restriction: 'error',
    style: 'error',
    suspicious: 'error',
  },
  plugins: ['eslint', 'import', 'oxc', 'promise', 'typescript', 'unicorn'],
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: 'error',
    typeAware: true,
  },
  rules: {
    'capitalized-comments': 'off',
    'id-length': ['error', { exceptionPatterns: ['[A-Z]'], exceptions: ['_', 'i'] }],
    'import/consistent-type-specifier-style': ['error', 'prefer-inline'],
    'import/group-exports': 'off',
    'import/max-dependencies': ['error', { ignoreTypeImports: true, max: 15 }],
    'import/no-named-export': 'off',
    'import/no-relative-parent-imports': 'off',
    'import/prefer-default-export': 'off',
    'no-magic-numbers': ['error', { ignore: [0, '0n', 1, 7, 24, 60, 1000] }],
    'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
    'no-ternary': 'off',
    'no-undefined': 'off',
    'max-lines': ['error', { skipBlankLines: true, skipComments: true }],
    'max-lines-per-function': ['error', { skipBlankLines: true, skipComments: true }],
    'max-statements': ['error', { max: 15 }],
    'sort-imports': 'off',
    'sort-keys': 'off',
    'typescript/array-type': ['error', { default: 'generic' }],
    'typescript/ban-ts-comment': 'off',
    'typescript/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/no-import-type-side-effects': 'off',
    'typescript/prefer-readonly-parameter-types': 'off',
    'unicorn/filename-case': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-null': 'off',
  },
});
